version: '3.8'

services:
  mongodb:
    image: mongo:5.0.18-focal
    networks:
      - lila-network

  redis:
    image: redis:alpine
    networks:
      - lila-network

  lila:
    build:
      context: docker
      dockerfile: lila.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./repos/lila:/lila
      - ./conf/lila.conf:/lila/conf/application.conf

  lila_ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./repos/lila-ws:/lila-ws
      - ./conf/lila-ws.conf:/lila-ws.conf

  nginx:
    image: nginx:alpine-slim
    networks:
      - lila-network
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./repos/lila/public:/lila/public
      - ./repos/lifat:/lifat
      - ./repos/chessground:/chessground
    depends_on:
      - lila
      - lila_ws

  api_docs:
    build:
      context: docker
      dockerfile: api-docs.Dockerfile
    ports:
      - 8089:8089
    volumes:
      - ./repos/api:/api

  pgn_viewer:
    build:
      context: docker
      dockerfile: pgn-viewer.Dockerfile
    ports:
      - 8090:8080
    volumes:
      - ./repos/pgn-viewer:/pgn-viewer

  lila_engine:
    build:
      context: docker
      dockerfile: lila-engine.Dockerfile
    networks:
      - lila-network
    ports:
      - 9666:9666
    volumes:
      - ./repos/lila-engine:/lila-engine
    profiles:
      - external-engine

  lila_fishnet:
    build:
      context: docker
      dockerfile: lila-fishnet.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./repos/lila-fishnet:/lila-fishnet
      - ./conf/lila-fishnet.conf:/lila-fishnet/conf/application.conf
    profiles:
      - stockfish

  fishnet_play:
    image: niklasf/fishnet
    entrypoint: /fishnet --endpoint http://lila_fishnet:9665/fishnet --max-backoff 5
    networks:
      - lila-network
    profiles:
      - stockfish

  fishnet_analysis:
    image: niklasf/fishnet
    entrypoint: /fishnet --endpoint http://lila:9663/fishnet --max-backoff 5
    networks:
      - lila-network
    profiles:
      - stockfish

  python:
    build:
      context: docker
      dockerfile: python.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./repos/lila-db-seed:/lila-db-seed

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - lila-network
    profiles:
      - search

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - lila-network
    depends_on:
      - elasticsearch
    profiles:
      - search

  lila_search:
    build:
      context: docker
      dockerfile: lila-search.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./lila-search:/lila-search
      - ./conf/lila-search.conf:/lila-search/conf/application.conf
    profiles:
      - search

  lila_gif:
    build:
      context: docker
      dockerfile: lila-gif.Dockerfile
    ports:
      - 6175:6175
    networks:
      - lila-network
    volumes:
      - ./repos/lila-gif:/lila-gif
    profiles:
      - images

  picfit:
    build:
      context: docker
      dockerfile: picfit.Dockerfile
    ports:
      - 3001:3001
    networks:
      - lila-network
    profiles:
      - images

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
    networks:
      - lila-network
  
  mongo_express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - lila-network
    depends_on:
      - mongodb

networks:
  lila-network:
    driver: bridge
