version: '3.8'

services:
  mongodb:
    image: mongo:5.0.15-focal
    networks:
      - lila-network

  redis:
    image: redis:alpine
    networks:
      - lila-network

  lila:
    build:
      context: docker
      dockerfile: lila.Dockerfile
    networks:
      - lila-network
    ports:
      - 9663:9663
    volumes:
      - ./lila:/lila
      - ./conf/lila.conf:/lila/conf/application.conf

  lila_ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    networks:
      - lila-network
    ports:
      - 9664:9664
    volumes:
      - ./lila-ws:/lila-ws
      - ./conf/lila-ws.conf:/lila-ws.conf

  lila_engine:
    build:
      context: docker
      dockerfile: lila-engine.Dockerfile
    networks:
      - lila-network
    ports:
      - 9666:9666
    volumes:
      - ./lila-engine:/lila-engine

  lila_fishnet:
    build:
      context: docker
      dockerfile: lila-fishnet.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./lila-fishnet:/lila-fishnet
      - ./conf/lila-fishnet.conf:/lila-fishnet/conf/application.conf

  fishnet_play:
    image: niklasf/fishnet
    entrypoint: /fishnet --endpoint http://lila_fishnet:9665/fishnet --max-backoff 5
    networks:
      - lila-network

  fishnet_analysis:
    image: niklasf/fishnet
    entrypoint: /fishnet --endpoint http://lila:9663/fishnet --max-backoff 5
    networks:
      - lila-network

  python:
    build:
      context: docker
      dockerfile: python.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./lila-db-seed:/lila-db-seed

  lila_gif:
    build:
      context: docker
      dockerfile: lila-gif.Dockerfile
    networks:
      - lila-network
    volumes:
      - ./lila-gif:/lila-gif

networks:
  lila-network:
    driver: bridge
