version: '3.8'

services:
  mongodb:
    image: mongo:5.0.15-focal
    networks:
      - lila-network
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    networks:
      - lila-network
    ports:
      - 6379:6379

  lila:
    build:
      context: docker
      dockerfile: lila.Dockerfile
    networks:
      - lila-network
    ports:
      - 9663:9663
    volumes:
      - ./lila:/lila
      - ./docker/conf/lila.conf:/lila/conf/application.conf
    depends_on:
      - mongodb
      - redis

  lila-ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    networks:
      - lila-network
    ports:
      - 9664:9664
    volumes:
      - ./lila-ws:/lila-ws
      - ./docker/conf/lila-ws.conf:/lila-ws.conf
    depends_on:
      - mongodb

  lila-engine:
    build:
      context: docker
      dockerfile: lila-engine.Dockerfile
    networks:
      - lila-network
    ports:
      - 9666:9666
    volumes:
      - ./lila-engine:/lila-engine

networks:
  lila-network:
    driver: bridge
